TebLocalPlannerROS:

  odom_topic: odom
  map_frame: /map

  #Trajectory

  # teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  min_samples: 3
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: false
  max_global_plan_lookahead_dist: 2.0
  global_plan_viapoint_sep: -0.1
  # global_plan_prune_distance: 1
  exact_arc_length: false
  feasibility_check_no_poses: 3  #检测位姿可到达的时间间隔
  publish_feedback: false  

  # Robot

  max_vel_x: 1.3  #最大速度
  max_vel_x_backwards: 1.1  #最大倒车速度
  # max_vel_y: 0.0
  max_vel_theta: 2.9
  acc_lim_x: 1.5  #最大加速度
  acc_lim_theta: 3.3

  # ********************** Carlike robot parameters ********************
  min_turning_radius: 0.25  #最小转向半径
  # heelbase: 0.4                 # Wheelbase of our robot
  # cmd_angle_instead_rotvel: True # stage simulator takes the angle instead of the rotvel as input (twist message)
  # ********************************************************************
  
  footprint_model:
    type: "polygon"
    vertices: [[0.171, -0.128], [0.171, 0.128],[-0.171, 0.128], [-0.171, -0.128]]

  # GoalTolerance

  yaw_goal_tolerance: 1  #目标角度偏移容忍度
  xy_goal_tolerance: 0.5  
  free_goal_vel: false
  # complete_global_plan: True

  # Obstacles

  min_obstacle_dist: 0.04  #与障碍物的最小期望距离/m
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0  #后方n米范围内的障碍物
  # obstacle_poses_affected: 15

  inflation_dist: 0.6  #障碍物周围缓冲区，大于最小期望距离有效
  # dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: false 

  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  # optimization_activate: True
  # optimization_verbose: False
  penalty_epsilon: 0.05  #w为速度的约束提供缓冲
  # obstacle_cost_exponent: 4
  weight_max_vel_x: 100.0  #最大速度权重
  weight_max_vel_theta: 1.0  #最大角速度权重
  weight_acc_lim_x: 1.0  #最大加速度权重 
  weight_acc_lim_theta: 1.0  #最大角加速度权重
  weight_kinematics_nh: 1000.0  #运动学的优化权重
  weight_kinematics_forward_drive: 1000.0  #0-1000，数值越大。倒车惩罚越大。
  weight_kinematics_turning_radius: 150.0  #1-1000，越大越容易达到最小转向半径。
  weight_optimaltime: 50  #0-1000 基于轨迹的时间上的权重 0-1000
  # weight_shortest_path: 0
  weight_obstacle: 50  #优化过程中，和障碍物最小距离的权重 0-1000
  weight_inflation: 0.1  #优化过程中，膨胀区的权重 0-1000
  # weight_dynamic_obstacle: 10 # not in use yet
  # weight_dynamic_obstacle_inflation: 0.2
  weight_viapoint: 1.0  #优化过程中，和全局路径采样点距离的权重  0-1000
  weight_adapt_factor: 2.0

  # Homotopy Class Planner

  enable_homotopy_class_planning: true
  enable_multithreading: true  #允许多线程并行处理
  max_number_classes: 4  #允许的线程数
  selection_cost_hysteresis: 1.0
  # selection_prefer_initial_plan: 0.95
  selection_obst_cost_scale: 100.0
  selection_alternative_time_cost: false

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  # roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: true
  # delete_detours_backwards: True
  # max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: false
  # visualize_with_time_as_z_axis_scale: False

  # Recovery

  shrink_horizon_backup: true  #当规划器检测到系统异常，允许缩小时域规划范围。
  shrink_horizon_min_duration: 10.0
  # oscillation_recovery: True
  # oscillation_v_eps: 0.1
  # oscillation_omega_eps: 0.1
  # oscillation_recovery_min_duration: 10
  # oscillation_filter_duration: 10


  force_reinit_new_goal_dist: 1.0  
  is_footprint_dynamic: false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5
  selection_viapoint_cost_scale: 1.0






